import { ErpState } from './types';

export const initialErpState: ErpState = {
  vendors: [
    {
      id: 'v-timber',
      name: 'Timber Craft Supplies',
      email: 'orders@timbercraft.com',
      phone: '+1 (555) 234-5678',
      address: '108 Sawmill Road, Timberville',
    },
    {
      id: 'v-hardware',
      name: 'Hardware Direct',
      email: 'sales@hardwaredirect.com',
      phone: '+1 (555) 876-5432',
      address: '404 Fastener Alley, Steel Town',
    },
    {
      id: 'v-craftwood',
      name: 'CraftWood Finishing Supplies',
      email: 'info@craftwood.com',
      phone: '+1 (555) 990-1122',
      address: '77 Coating Park, Industrial Zone',
    },
  ],
  products: [
    {
      id: 'p-table',
      name: 'Wooden Table',
      sku: 'TBL-001',
      category: 'Finished Good',
      salesPrice: 250,
      costPrice: 120,
      onHandQty: 2,
      reservedQty: 0,
      procurementStrategy: 'MTO',
      procurementType: 'Manufacturing',
      procureOnDemand: true,
      bomId: 'bom-table',
      createdAt: '2026-07-01T09:00:00Z',
    },
    {
      id: 'p-chair',
      name: 'Wooden Chair',
      sku: 'CHR-001',
      category: 'Finished Good',
      salesPrice: 80,
      costPrice: 35,
      onHandQty: 100,
      reservedQty: 10,
      procurementStrategy: 'MTS',
      procurementType: 'Manufacturing',
      procureOnDemand: false,
      bomId: 'bom-chair',
      createdAt: '2026-07-02T10:00:00Z',
    },
    {
      id: 'p-dining',
      name: 'Dining Table',
      sku: 'TBL-002',
      category: 'Finished Good',
      salesPrice: 450,
      costPrice: 210,
      onHandQty: 5,
      reservedQty: 0,
      procurementStrategy: 'MTO',
      procurementType: 'Manufacturing',
      procureOnDemand: true,
      bomId: 'bom-dining',
      createdAt: '2026-07-03T11:00:00Z',
    },
    {
      id: 'p-leg',
      name: 'Wooden Legs',
      sku: 'RAW-LEG',
      category: 'Component',
      salesPrice: 20,
      costPrice: 15,
      onHandQty: 50,
      reservedQty: 0,
      procurementStrategy: 'MTS',
      procurementType: 'Purchase',
      procureOnDemand: true,
      vendorId: 'v-timber',
      createdAt: '2026-07-01T08:00:00Z',
    },
    {
      id: 'p-top',
      name: 'Wooden Top',
      sku: 'RAW-TOP',
      category: 'Component',
      salesPrice: 50,
      costPrice: 40,
      onHandQty: 15,
      reservedQty: 0,
      procurementStrategy: 'MTS',
      procurementType: 'Purchase',
      procureOnDemand: true,
      vendorId: 'v-timber',
      createdAt: '2026-07-01T08:30:00Z',
    },
    {
      id: 'p-screw',
      name: 'Screws (Pack of 12)',
      sku: 'RAW-SCR',
      category: 'Raw Material',
      salesPrice: 5,
      costPrice: 2,
      onHandQty: 200,
      reservedQty: 0,
      procurementStrategy: 'MTS',
      procurementType: 'Purchase',
      procureOnDemand: true,
      vendorId: 'v-hardware',
      createdAt: '2026-07-01T08:45:00Z',
    },
  ],
  boms: [
    {
      id: 'bom-table',
      name: 'Wooden Table Standard BoM',
      productId: 'p-table',
      outputQty: 1,
      description: 'Standard 4-legged wooden desk assembly',
      components: [
        { id: 'bc-1', bomId: 'bom-table', componentProductId: 'p-leg', quantity: 4 },
        { id: 'bc-2', bomId: 'bom-table', componentProductId: 'p-top', quantity: 1 },
        { id: 'bc-3', bomId: 'bom-table', componentProductId: 'p-screw', quantity: 1 },
      ],
      operations: [
        { id: 'bo-1', bomId: 'bom-table', name: 'Assembly', workCenter: 'Assembly Line 1', durationMinutes: 60, stepOrder: 1 },
        { id: 'bo-2', bomId: 'bom-table', name: 'Painting & Varnish', workCenter: 'Paint Floor', durationMinutes: 30, stepOrder: 2 },
        { id: 'bo-3', bomId: 'bom-table', name: 'Quality Check & Packaging', workCenter: 'Packaging Unit', durationMinutes: 20, stepOrder: 3 },
      ],
    },
    {
      id: 'bom-chair',
      name: 'Wooden Chair Standard BoM',
      productId: 'p-chair',
      outputQty: 1,
      description: 'Ergonomic wooden chair structure',
      components: [
        { id: 'bc-4', bomId: 'bom-chair', componentProductId: 'p-leg', quantity: 4 },
        { id: 'bc-5', bomId: 'bom-chair', componentProductId: 'p-screw', quantity: 1 },
      ],
      operations: [
        { id: 'bo-4', bomId: 'bom-chair', name: 'Frame Assembly', workCenter: 'Assembly Line 2', durationMinutes: 30, stepOrder: 1 },
        { id: 'bo-5', bomId: 'bom-chair', name: 'Sanding & Finish', workCenter: 'Paint Floor', durationMinutes: 15, stepOrder: 2 },
      ],
    },
    {
      id: 'bom-dining',
      name: 'Dining Table Deluxe BoM',
      productId: 'p-dining',
      outputQty: 1,
      description: 'Large 6-person hardwood dining table',
      components: [
        { id: 'bc-6', bomId: 'bom-dining', componentProductId: 'p-leg', quantity: 6 },
        { id: 'bc-7', bomId: 'bom-dining', componentProductId: 'p-top', quantity: 2 },
        { id: 'bc-8', bomId: 'bom-dining', componentProductId: 'p-screw', quantity: 2 },
      ],
      operations: [
        { id: 'bo-6', bomId: 'bom-dining', name: 'Heavy Frame Assembly', workCenter: 'Assembly Line 1', durationMinutes: 90, stepOrder: 1 },
        { id: 'bo-7', bomId: 'bom-dining', name: 'Staining & Sealing', workCenter: 'Paint Floor', durationMinutes: 45, stepOrder: 2 },
        { id: 'bo-8', bomId: 'bom-dining', name: 'Crate Packaging', workCenter: 'Packaging Unit', durationMinutes: 30, stepOrder: 3 },
      ],
    },
  ],
  salesOrders: [
    {
      id: 'so-001',
      orderNumber: 'SO-2026-001',
      customerName: 'Acme Commercial Spaces',
      customerEmail: 'procurement@acme.com',
      status: 'confirmed',
      totalAmount: 800,
      createdAt: '2026-07-20T14:30:00Z',
      items: [
        {
          id: 'soi-1',
          salesOrderId: 'so-001',
          productId: 'p-chair',
          productName: 'Wooden Chair',
          orderedQty: 10,
          deliveredQty: 0,
          unitPrice: 80,
        },
      ],
    },
    {
      id: 'so-002',
      orderNumber: 'SO-2026-002',
      customerName: 'Shiv Furnishings Direct',
      customerEmail: 'sales@shivfurnishings.com',
      status: 'draft',
      totalAmount: 2500,
      createdAt: '2026-07-25T16:00:00Z',
      items: [
        {
          id: 'soi-2',
          salesOrderId: 'so-002',
          productId: 'p-table',
          productName: 'Wooden Table',
          orderedQty: 10,
          deliveredQty: 0,
          unitPrice: 250,
        },
      ],
    },
  ],
  purchaseOrders: [
    {
      id: 'po-001',
      orderNumber: 'PO-2026-001',
      vendorName: 'Timber Craft Supplies',
      vendorId: 'v-timber',
      status: 'received',
      totalAmount: 750,
      createdAt: '2026-07-15T10:00:00Z',
      items: [
        {
          id: 'poi-1',
          purchaseOrderId: 'po-001',
          productId: 'p-leg',
          productName: 'Wooden Legs',
          orderedQty: 50,
          receivedQty: 50,
          unitCost: 15,
        },
      ],
    },
  ],
  manufacturingOrders: [
    {
      id: 'mo-001',
      orderNumber: 'MO-2026-001',
      productId: 'p-chair',
      productName: 'Wooden Chair',
      bomId: 'bom-chair',
      targetQty: 20,
      producedQty: 20,
      status: 'completed',
      assignee: 'Rajesh Sharma (Lead Assembler)',
      workOrders: [
        { id: 'wo-1', manufacturingOrderId: 'mo-001', name: 'Frame Assembly', workCenter: 'Assembly Line 2', durationMinutes: 30, status: 'completed', completedAt: '2026-07-18T12:00:00Z' },
        { id: 'wo-2', manufacturingOrderId: 'mo-001', name: 'Sanding & Finish', workCenter: 'Paint Floor', durationMinutes: 15, status: 'completed', completedAt: '2026-07-18T14:30:00Z' },
      ],
      createdAt: '2026-07-17T09:00:00Z',
    },
  ],
  stockLedger: [
    {
      id: 'sl-1',
      productId: 'p-leg',
      productName: 'Wooden Legs',
      referenceType: 'PO',
      referenceId: 'PO-2026-001',
      changeQty: 50,
      resultingOnHand: 50,
      resultingReserved: 0,
      notes: 'Initial material stock receipt from Timber Craft Supplies',
      createdAt: '2026-07-15T10:15:00Z',
      createdBy: 'System (Purchase Module)',
    },
    {
      id: 'sl-2',
      productId: 'p-chair',
      productName: 'Wooden Chair',
      referenceType: 'MO_PRODUCTION',
      referenceId: 'MO-2026-001',
      changeQty: 20,
      resultingOnHand: 100,
      resultingReserved: 10,
      notes: 'Finished goods output from MO-2026-001',
      createdAt: '2026-07-18T15:00:00Z',
      createdBy: 'Rajesh Sharma',
    },
  ],
  auditLogs: [
    {
      id: 'al-1',
      entityType: 'PurchaseOrder',
      entityId: 'po-001',
      action: 'RECEIPT',
      details: 'Received 50 units of Wooden Legs from Timber Craft Supplies. Stock updated.',
      userName: 'Purchase Manager',
      createdAt: '2026-07-15T10:15:00Z',
    },
    {
      id: 'al-2',
      entityType: 'ManufacturingOrder',
      entityId: 'mo-001',
      action: 'PRODUCED',
      details: 'Completed MO-2026-001 for 20 Wooden Chairs. Consumed 80 Wooden Legs and 20 Screws.',
      userName: 'Rajesh Sharma',
      createdAt: '2026-07-18T15:00:00Z',
    },
    {
      id: 'al-3',
      entityType: 'SalesOrder',
      entityId: 'so-001',
      action: 'STATUS_CHANGE',
      details: 'Sales Order SO-2026-001 confirmed for Acme Commercial Spaces. Reserved 10 Wooden Chairs.',
      userName: 'Sales Rep',
      createdAt: '2026-07-20T14:30:00Z',
    },
  ],
};
